[package]
name = "rvmx"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
incremental = true
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
